name: Build APK
on: [workflow_dispatch]

jobs:
  Gradle:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: setup jdk
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Make Gradle executable
      run: chmod +x ./src/gradlew
    - name: Build Release APK
      run: |
        cd ./src
        ./gradlew build
    - name: Upload apk
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: src/app/build/outputs
        
